### PR TITLE
Mount pacman private-keys-v1 as tmpfs

### LINKED ISSUE #6242: Privilege escalation vulnerability in Arch templates
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

`builder-archlinux`

**Brief summary**

`/etc/pacman.d/gnupg/private-keys-v1.d` is non-empty in Arch templates.  The keys within it can be used to sign packages that Pacman will trust.  This allows any Arch Linux AppVM or DispVM to compromise its template.

To exploit this vulnerability, an attacker needs:

- Root access to the AppVM or DispVM.  This is not considered an obstacle.
- The ability to get Pacman to install a package they have signed with the stolen key.  This requires an on-path attack (MITM) or control over a mirror Pacman will use.

**How Reproducible**

100%

**To Reproduce**

1. Build an Arch template
2. Run `sudo gpg2 --homedir=/etc/pacman.d/gnupg --list-secret-keys` in the template.

**Expected behavior**

The list is empty, since `/etc/pacman.d/gnupg` is readable by all VMs based on the TemplateVM.

**Actual behavior**

The list is not empty.

**Screenshots**

**Additional context**

The Arch package management system, Pacman, relies on a secret, per-machine master key readable only by root.  This is used to sign the other Arch root signing keys.  Anyone with access to the secret part of the master key can present packages that Pacman will trust, and thus execute arbitrary code as root.

In typical use, this is fine, since the master key is securely generated and only readable by root.  This is normally sufficient to prevent the secret part of the key from being accessed by unauthorized parties.  However, in QubesOS, this is not sufficient.  The master key is stored on the root volume, so it is accessible to all AppVMs based on the TemplateVM.  Anyone who compromises one of these AppVMs can dump the secret master key.  If they can then perform an on-path attack on the update process, this allows them to execute arbitrary code on the TemplateVM as root.

Worse, if a TemplateVM is distributed as an RPM, anyone in possession of the RPM can compromise any Arch VM installed from the RPM.

**Solutions you've tried**

Mounting `/etc/pacman.d/gnupg/private-keys-v1.d` as a tmpfs (both during the build and in the installed template) will mitigate the vulnerability, as it will be discarded on VM shutdown.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

### PR DESCRIPTION
**Pull request by ejose19**
Fixes: https://github.com/QubesOS/qubes-issues/issues/6242

As mentioned by @DemiMarie on, this should prevent a compromised AppVM to sign packages that the TemplateVM will trust (by mounting that folder as tmpfs on both builder and template).

### CODE REVIEW

File: scripts/arch-chroot-lite [hunk 1]
```diff
@@ -30,7 +30,8 @@ chroot_setup() {
     chroot_add_mount devpts "$1/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec &&
     chroot_add_mount shm "$1/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
     chroot_add_mount run "$1/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
-    chroot_add_mount tmp "$1/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
+    chroot_add_mount tmp "$1/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid &&
+    chroot_add_mount pacman-privkeys "$1/etc/pacman.d/gnupg/private-keys-v1.d" -t tmpfs -o mode=600,nosuid,noexec
```
Comment (DemiMarie) [inline scripts/arch-chroot-lite]:
```suggestion
    chroot_add_mount pacman-privkeys "$1/etc/pacman.d/gnupg/private-keys-v1.d" -t tmpfs -o mode=600,nosuid,noexec,nodev ||
    exit
```

We need to exit if the mount fails for any reason.

File: scripts/04_install_qubes.sh [hunk 2]
```diff
@@ -71,7 +71,8 @@ cat >> "${INSTALLDIR}/etc/fstab" <<EOF
 /rw/usrlocal    /usr/local  none    noauto,bind,defaults 0 0
 
 # Template Customizations
-tmpfs                   /dev/shm                tmpfs   defaults,size=1G        0 0
+tmpfs                   /dev/shm                                    tmpfs   defaults,size=1G            0 0
+tmpfs                   /etc/pacman.d/gnupg/private-keys-v1.d       tmpfs   defaults,noexec,mode=600    0 0
```
Comment (DemiMarie) [inline scripts/04_install_qubes.sh]:
```suggestion
tmpfs                   /etc/pacman.d/gnupg/private-keys-v1.d       tmpfs   defaults,noexec,nosuid,nodev,mode=600    0 0
```

**Review by DemiMarie — CHANGES_REQUESTED** [review]
We need to move the `pacman-key --init` and `pacman-key --populate` calls into a single call to `scripts/arch-chroot-lite`, so that `pacman-key --populate` has access to the signing key.

**Comment by ejose19** [comment]
Ok, should be good now. Thanks for the review

**Comment by DemiMarie** [comment]
@marmarek can you merge this?

**Review by marmarek — APPROVED** [review]
This will break adding extra keys - like in #42 (archlinux.qubes-os.org repo), but we can fix it there.
Thanks @ejose19
